version: "3"
services:

  wiremock_base:
    image: "wiremock/wiremock:latest"
    ports:
      - 8080:8080
    volumes:
      - ./.wiremock/mappings_base/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]

  wiremock_new:
    image: "wiremock/wiremock:latest"
    ports:
      - 8081:8080
    volumes:
      - ./.wiremock/mappings_new/mappings:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]
